nbc-final-team2/ddaraogae

app/src/main/AndroidManifest.xml, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/MainActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/PrivacyFragment.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/onboard/InputImageFragment.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/onboard/InputInfoFragment.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/onboard/InputNameFragment.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt, app/src/main/res/layout/activity_add.xml, app/src/main/res/layout/activity_finish.xml, app/src/main/res/layout/activity_history.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_input_image.xml, app/src/main/res/layout/fragment_input_info.xml, app/src/main/res/layout/fragment_input_name.xml, app/src/main/res/layout/fragment_mypage.xml, app/src/main/res/layout/fragment_privacy.xml, app/src/main/res/layout/fragment_walk.xml
- presentation package분리
- 필요한 화면 kt파일 layout 생성
resolved: #2
=> presentation package 분리

app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/DogEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/SpotEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StampEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/WalkingEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/DogRepository.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/SpotRepository.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/StampRepository.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/WalkingRepository.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/WeatherRepository.kt
=> Entity 추가 및 기본 Repository 구성

app/build.gradle.kts, app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/EmailAuthEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/UserEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/AuthRepository.kt, gradle/libs.versions.toml
1. 이메일 링크 인증, 회원 탈퇴 등은 포함되어 있지 않음
resolved #16
=> 기본 이메일, 구글 로그인 및 회원가입 기능 구현

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginUiState.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt, app/src/main/res/values/strings.xml
=> [Feat] google 로그인

app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/FirebaseMapper.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/DogEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/EmailAuthEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/LatLngEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StampEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/UserEntity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/WalkingEntity.kt
=> Data 및 Domain 모델 프로퍼티 nullable 처리

app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/DogRepositoryImpl.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/EmailAuthEntity.kt
=> nullable 처리 하면서 발생한 오류 픽스

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/FirebaseModule.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSource.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/DogRepositoryImpl.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/DogRepository.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertDogUseCase.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/InsertDogUseCaseImpl.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateDogUseCase.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/UpdateDogUseCaseImpl.kt, gradle/libs.versions.toml
resolved: #54 
---
새롭게 UseCase가 추가되거나 하지는 않아서 새롭게 호출해야하는 함수는 없습니다(data layer 단에서 처리됨).
---
test 영상입니다.
(test시 사용한 activity, viewmodel 코드는 PR에 포함되어있지 않습니다.)
https://github.com/nbc-final-team2/ddaraogae/assets/128209823/40fe0b11-a01f-48cd-a6c9-30a778a4318c
=> 이미지 저장 로직 구현

app/src/main/AndroidManifest.xml, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/service/LocationService.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DistanceCalculator.kt, app/src/main/res/layout/activity_main.xml
- 소실된 manifest 코드 복구
- km 단위로 거리 제공하기 위해 DistanceCalculator 값 수정
resolved: #80
=> Location Service 내에서 거리 계산하도록 기능 추가

app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/UseCaseModule.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSource.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StampRepositoryImpl.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/repository/StampRepository.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampListByPeriodUseCase.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampListByPeriodUseCaseImpl.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampNumByPeriodUseCase.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/usecase/GetStampNumByPeriodUseCaseImpl.kt
- 반려견과 스탬프는 더 이상 관계가 없으므로, 관련 비즈니스 로직 변경했습니다(더 이상 dogId를 요구하지 않음)
- 추후 사용할 일이 생길 것 같아서, getStampListByPeriodUseCase()를 추가했습니다(스탬프의 수가 아닌 리스트 자체를 가져옴)
- 수정 및 추가한 로직들은 기초적으로 테스트 해봤고, 정상적으로 작동했습니다
resolved: #101
=> 스탬프 관련 비즈니스 로직 변경

app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/main/TestViewModel.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypageFragment.kt
- 유저가 생성한 하위 문서 하나하나 삭제 하도록 변경
resolved: #115
=> 유저 삭제 로직 변경

app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
- 산책 이후, 반려견 별로 id 값 넣어 각각의 산책 데이터 생성하도록 변경
resolved: #127
=> 산책 데이터 업로드 로직 수정

app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/SignUpActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/MypagePrivacyActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/FinishActivity.kt
모든 Activity 앱 상태바, 네비게이션바 통일 수정 완료
resoved: #129
=> 앱 상태바, 네비게이션바 통일 수정 완료

app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/AuthRepositoryImpl.kt
=> 회원탈퇴 버그 수정

app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/model/DefaultEvent.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/SharedEvent.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/shared/SharedEventViewModel.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddPetViewModel.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddUiState.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt, app/src/main/res/values/strings.xml
- SharedFlow 이용하도록 Add 화면 수정
issue: #136
=> 반려견 추가 화면 리팩터링

app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/loading/LoadingDialog.kt, app/src/main/res/layout/activity_log_in.xml, app/src/main/res/layout/dialog_loading.xml
- 아직 설정을 할 수가 없어 기능만 추가해놨습니다.
- ui 안에 loading 패키지 따로 만들어놨습니다.
- 기존에 로그인 화면 버튼 UI가 이상하던것 수정했습니다.
resolved: #145
=> 로딩 기능 추가및 로그인화면 UI 버그 수정

app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
https://github.com/nbc-final-team2/ddaraogae/pull/165
conflict를 github 내에서 mark resolved하면서 if문 빠진걸 확인을 못해서 급하게 다시 pr 올립니다.
아마 develop에서 pull 받으신분들은 해당 부분 때문에 run이 안될 겁니다
=> fix: conflict markresolved하고 if문이 빠져서 빌드 안되는 문제 해결

app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddPetViewModel.kt
제 코드가 늦게 반영돼서, 기존 로딩 처리를 위한 코드가 남아있는 채로 병합됐네요
추후에 StateFlow 이용해서 따로 처리할 거라 삭제했습니다
컴파일도 안되는 상황이라 급하게 수정 해야해서 먼저 PR 올립니다
see also: #177
=> 기존 DefaultEvent.Loading 잔재 코드 제거

app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetViewModel.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/UpdateTaskState.kt
이것도 기존 로딩 처리 코드가 남아서 정상 작동을 막고 있어 삭제했습니다
see also: #177
=> 기존 로딩 처리 삭제

.gitignore
keystore 폴더에 대한 gitignore 처리를 해두었습니다!
아까전 PR에서 이것도 해둘걸 그랬네요..
=> keystore 폴더가 git에 올리는 파일 대상이 되지 않도록 수정

app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
=> 맵 초기화 전 현재 위치 버튼 누르면 죽는 문제 해결

app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddPetViewModel.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddUiState.kt
모든 PR 병합 기다리다가, 큰 충돌 안 날 것 같고 더 기다리면 늦어질 것 같아
미리 작성해서 올립니다
Add 화면 쪽에 loading ui 추가 했고, history나 home쪽은 다중 호출로 인해 위험할 수 있는 쓰기 작업이 없어서 처리하지 않았습니다
resolved: #177
=> 로딩 UI 적용(2차)

app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/GraphUtils.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HistoryActivity.kt, app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
그래프 배경색 회색보단 흰색이 나은 것 같아서 변경해 봤습니다.
=> [fix] 그래프 배경 색 회색 -> 흰색

app/src/main/res/layout/fragment_walk.xml
resolved: #203 
일단 좋은 방법이 없는것 같아서 왼쪽으로 위치를 바꿨는데 어떤가요? 별로거나 다른 방법이 있으면 close하겠습니다.
=> 맵 내 현재 위치 버튼 줌 인/아웃에 맞추기
